PouyaTechBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from PouyaTechBlog import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("home_app.urls")),
                  path("", include("post_detail_app.urls")),
                  path("", include("account_app.urls")),
                  path("", include("contact_us_app.urls")),
                  path("addpost", include("add_post_app.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views

app_name = "account_app"

urlpatterns = [
    path("leave", views.leave, name="leave"),
    path("join", views.join, name="join"),
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("search", views.search, name="search_posts"),
    path("profile/<slug:slug>/<int:pk>", views.profile, name="profile"),
    path("edit-profile", views.edit_profile, name="edit_profile"),
    path("delete-profile", views.delete_profile, name="delete_profile"),
]

post_detail_app/urls.py
from django.urls import path
from . import views

app_name = "post_detail_app"

urlpatterns = [
    path("details/<slug:slug>", views.post_detail, name="post_detail"),
    path("category/<int:pk>", views.category_detail, name="category_detail"),
    path("like/<slug:slug>/<int:pk>", views.like, name="like"),
    path("dislike/<slug:slug>/<int:pk>", views.dislike, name="dislike"),
    path("dislike/<slug:slug>/<int:pk>", views.dislike, name="dislike"),
]

home_app/models.py
from django.db import models

# Create your models here.

home_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from account_app.models import Profile
import datetime
import string

allowed_characters = []
for _ in string.ascii_letters:
    allowed_characters.append(_)
for __ in range(0, 10):
    allowed_characters.append(str(__))
allowed_characters.append("_")
allowed_characters.append("-")
allowed_characters.append("/")
allowed_characters.append("|")

birth_date_choices = []

for _ in range(datetime.datetime.today().year - 101, datetime.datetime.today().year):
    birth_date_choices.append(_)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "username_label", "first_name", "last_name", "bio", "email", "image", "gender", "birth_date",
            "phone_number")
        widgets = {
            "username_label": forms.TextInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (200 characters)",
                       "style": "font-size: 20px; border-radius: 20px"}),
            "first_name": forms.TextInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (50 characters)",
                       "style": "font-size: 20px; border-radius: 20px"}),
            "last_name": forms.TextInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (50 characters)",
                       "style": "font-size: 20px; border-radius: 20px"}),
            "bio": forms.TextInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (100 characters)",
                       "style": "font-size: 20px; border-radius: 20px"}),
            "email": forms.EmailInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (∞ characters)",
                       "style": "font-size: 20px; border-radius: 20px; color: red; border-color: red"}),
            "phone_number": forms.TextInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (20 characters)",
                       "style": "font-size: 20px; border-radius: 20px; color: red; border-color: red"}),
            "image": forms.FileInput(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (75 characters)",
                       "style": "font-size: 20px; border-radius: 20px"}),
            "gender": forms.Select(
                attrs={"class": "form-control mr-0 ml-auto", "placeholder": "Max length (75 characters)",
                       "style": "font-size: 20px; border-radius: 20px; color: red; border-color: red"}),
            "birth_date": forms.SelectDateWidget(years=birth_date_choices,
                                                 attrs={"class": "form-control mr-0 ml-auto",
                                                        "placeholder": "Max length (75 characters)",
                                                        "style": "font-size: 20px; border-radius: 20px;"
                                                                 "color: red; border-color: red"}),
        }

    def clean_username_label(self):
        user_name = self.cleaned_data.get("username_label")

        if len(str(user_name)) < 2:
            raise ValidationError("Username must have at least 2 characters!")

        if str(user_name).isnumeric():
            raise ValidationError("Username must have at least 1 letter!")

        for single_character_checker in user_name:
            if single_character_checker not in allowed_characters:
                raise ValidationError(
                    "Unsupported format! (Just letters , numbers , '/' , '|' , '_' and '-' is allowed!)")

        return user_name

    def clean_email(self):
        email = self.cleaned_data.get("email")

        try:
            email_exists = User.objects.get(email=email)
            email_exists = email_exists.email
        except:
            email_exists = None

        if email_exists is not None and email_exists != self.cleaned_data.get("email"):
            raise ValidationError("This E-mail has been already taken!")

        return email

    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")

        if len(str(first_name)) < 2:
            raise ValidationError("First name must have at least 2 characters!")

        if not str(first_name).isalpha():
            raise ValidationError("First name must only contain letters!")

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get("last_name")

        if len(str(last_name)) < 2:
            raise ValidationError("Last name name must have at least 2 characters!")

        if not str(last_name).isalpha():
            raise ValidationError("Last name name must only contain letters!")

        return last_name

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")

        try:
            phone_number_exists = Profile.objects.get(phone_number=phone_number)
            phone_number_exists = phone_number_exists.phone_number
        except:
            phone_number_exists = None

        if phone_number_exists is not None and phone_number_exists != self.cleaned_data.get("phone_number"):
            raise ValidationError("This Phone number has been already taken!")

        return phone_number

    def clean(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")

        if last_name is None and first_name is not None:
            raise ValidationError("If you have a first name , You should fill your last name too!")
        elif first_name is None and last_name is not None:
            raise ValidationError("If you have a last name , You should fill your first name too!")

home_app/views.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from account_app.models import Profile
from home_app.forms import ProfileEditForm
from post_detail_app.models import Category, Post
from post_detail_app import models as post_detail_app_models
import datetime
from datetime import datetime

today = (datetime.today().date())


def home(request):
    post_objects = post_detail_app_models.Post.objects.order_by("-created_at")
    page_number = request.GET.get('page')
    paginator = Paginator(post_objects, 10)
    objects_list = paginator.get_page(page_number)
    all_authors = User.objects.all()

    return render(request, "home_app/index.html",
                  context={"post_objects": objects_list, "today": today, "all_authors": all_authors})


def category_detail(request, pk=None):
    category = Category.objects.get(id=pk)
    post_objects = category.article_set.all()
    return render(request, "home_app/index.html", context={"post_objects": post_objects})


def search(request):
    q = request.GET.get("q")
    post_objects = Post.objects.filter(title__icontains=q)

    if len(post_objects) == 0:
        post_objects = Post.objects.filter(body__icontains=q)

    page_number = request.GET.get('page')
    paginator = Paginator(post_objects, 10)
    objects_list = paginator.get_page(page_number)
    all_authors = User.objects.all()

    return render(request, "home_app/index.html", context={"post_objects": objects_list, "all_authors": all_authors})


def profile(request, slug, pk):
    if request.user.is_authenticated:

        post_datas = Post.objects.filter(author=pk, is_allowed=True).order_by("-created_at")
        page_number = request.GET.get('page')
        paginator = Paginator(post_datas, 10)
        post_list = paginator.get_page(page_number)
        personal_data = User.objects.get(username=slug)
        all_users = User.objects.all()
        return render(request, "home_app/profile.html",
                      context={"post_datas": post_datas, "personal_data": personal_data, "all_users": all_users,
                               "post_list": post_list})

    else:
        return redirect("account_app:join")


def edit_profile(request):
    if request.user.is_authenticated:
        username_taken = "0"
        email_taken = "0"
        profile = Profile.objects.get(username=request.user)
        profile_edit_form = ProfileEditForm(instance=profile)
        if request.method == "POST":
            profile_edit_form = ProfileEditForm(request.POST, request.FILES,
                                                instance=profile)
            if profile_edit_form.is_valid():
                all_usernames = []
                for _ in User.objects.all():
                    all_usernames.append(_.username)
                all_emails = []
                for _ in User.objects.all():
                    all_emails.append(_.email)
                # if profile_edit_form.cleaned_data.get("username_label") in all_usernames:
                if profile_edit_form.cleaned_data.get("username_label") == str(request.user):
                    user_to_be_saved = User.objects.get(username=request.user)
                    user_to_be_saved.username = profile_edit_form.cleaned_data.get("username_label")
                    user_to_be_saved.first_name = profile_edit_form.cleaned_data.get("first_name")
                    user_to_be_saved.last_name = profile_edit_form.cleaned_data.get("last_name")
                    user_to_be_saved.email = profile_edit_form.cleaned_data.get("email")
                    user_to_be_saved.save()
                    profile_edit_form.save()
                    return redirect("home_app:edit_profile")
                else:
                    if profile_edit_form.cleaned_data.get("username_label") in all_usernames:
                        username_taken = "This username has been already taken!"
                    else:
                        user_to_be_saved = User.objects.get(username=request.user)
                        user_to_be_saved.username = profile_edit_form.cleaned_data.get("username_label")
                        user_to_be_saved.first_name = profile_edit_form.cleaned_data.get("first_name")
                        user_to_be_saved.last_name = profile_edit_form.cleaned_data.get("last_name")
                        user_to_be_saved.email = profile_edit_form.cleaned_data.get("email")
                        user_to_be_saved.save()
                        profile_edit_form.save()
                        return redirect("home_app:edit_profile")

                return render(request, "home_app/edit_profile.html",
                              context={"profile_edit_form": profile_edit_form, "username_taken": username_taken})

        return render(request, "home_app/edit_profile.html",
                      context={"profile_edit_form": profile_edit_form})

    else:
        return redirect("home_app:home")


def delete_profile(request):
    if request.user.is_authenticated:
        request.user.delete()
        return redirect("home_app:home")

home_app/templates/home_app/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block contact_us %}
    class="tm-nav-item active"
{% endblock %}

{% block title %}
    {{ request.user }}'s edit profile
{% endblock %}

{% block profile %}
    class="tm-nav-item active"
{% endblock %}

{% block home_page %}
    class="tm-nav-item"
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <main class="tm-main">

            <div class="row tm-row tm-mb-45">
                <div class="col-12">
                    <hr class="tm-hr-primary tm-mb-55">
                </div>
            </div>
            <div class="row tm-row tm-mb-120">
                <div class="alert alert-danger" style="border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px;"><p style="color: red; display: inline-block">💀Red</p>
                    fields are critical ! You can't change them later.
                </div>
                <div class="col-12">
                    <h2 class="tm-color-primary tm-post-title tm-mb-60">Edit</h2>
                </div>
                <div class="col-lg-7 tm-contact-left">
                    <form method="POST" action="" class="mb-5 ml-auto mr-0 tm-contact-form"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if profile_edit_form.non_field_errors %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% if error != None %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ error }}
                            </div>
                        {% endif %}
                        {% if profile_edit_form.username_label.errors %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.username_label.errors }}
                            </div>
                        {% else %}
                            {% if username_taken == 'This username has been already taken!' %}
                                <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                    <li style="color: black">
                                        {{ username_taken }}
                                    </li>
                                </div>
                            {% endif %}
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Username</label>
                            <div class="col-sm-9">
                                {{ profile_edit_form.username_label }}
                            </div>
                        </div>
                        {% if profile_edit_form.first_name.errors %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.first_name.errors }}
                            </div>
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">First name</label>
                            <div class="col-sm-9">
                                {{ profile_edit_form.first_name }}
                            </div>
                        </div>
                        {% if profile_edit_form.last_name.errors %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.last_name.errors }}
                            </div>
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Last name</label>
                            <div class="col-sm-9">
                                {{ profile_edit_form.last_name }}
                            </div>
                        </div>
                        {% if profile_edit_form.bio.errors %}
                            <div class="alert alert-danger" style=" border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.bio.errors }}
                            </div>
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Bio</label>
                            <div class="col-sm-9">
                                {{ profile_edit_form.bio }}
                            </div>
                        </div>
                        {% if profile_edit_form.email.errors %}
                            <div class="alert alert-danger" style="border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.email.errors }}
                            </div>
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Image</label>
                            <div class="col-sm-9">
                                {{ profile_edit_form.image }}
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">E-mail</label>
                            <div class="col-sm-9" style="pointer-events: none;">
                                {{ profile_edit_form.email }}
                            </div>
                        </div>
                        {% if profile_edit_form.phone_number.errors %}
                            <div class="alert alert-danger" style="border-top-left-radius: 50px;
                             border-bottom-right-radius: 50px; border-top-right-radius: 20px;
                             border-bottom-left-radius: 20px; display: inline-block; align-content: center">
                                {{ profile_edit_form.phone_number.errors }}
                            </div>
                        {% endif %}
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Number</label>
                            {% if request.user.profile.phone_number == None %}
                                <div class="col-sm-9">
                                    {{ profile_edit_form.phone_number }}
                                </div>
                            {% else %}
                                <div class="col-sm-9" style="pointer-events: none">
                                    {{ profile_edit_form.phone_number }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Gender</label>
                            {% if request.user.profile.gender == "rather not to say" %}
                                <div class="col-sm-9">
                                    {{ profile_edit_form.gender }}
                                </div>
                            {% else %}
                                <div class="col-sm-9" style="pointer-events: none">
                                    {{ profile_edit_form.gender }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group row mb-4">
                            <label style="font-size: 20px"
                                   class="col-sm-3 col-form-label text-right tm-color-primary">Birth date</label>
                            {% if request.user.profile.birth_date == None %}
                                <div class="col-sm-9">
                                    {{ profile_edit_form.birth_date }}
                                </div>
                            {% else %}
                                <div class="col-sm-9" style="pointer-events: none">
                                    {{ profile_edit_form.birth_date }}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group row text-right">
                            <div class="col-12">
                                <button style="width:100% ;height: 85%" class="tm-btn tm-btn-primary tm-btn-small">
                                    Submit
                                </button>
                            </div>
                        </div>
                        <br>
                        <div>
                            <div class="col-12">
                                <a href="{% url 'home_app:delete_profile' %}">
                                    <div style="width: 100%; height: 120%" class="btn btn-danger">
                                        Delete your account
                                    </div>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

home_app/templates/home_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    PouyaTech Blog
{% endblock %}

{% block home_page %}
    class="tm-nav-item active"
{% endblock %}

{% block contact_us %}
    class="tm-nav-item"
{% endblock %}

{% block add_post %}
    class="tm-nav-item"
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <main class="tm-main">
            <div class="row tm-row">
                {% for post_object in post_objects %}
                    {% if post_object.is_allowed %}
                        <article class="col-12 col-md-6 tm-post">
                            <hr class="tm-hr-primary">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'post_detail_app:post_detail' post_object.slug %}"
                                   class="effect-lily tm-post-link tm-pt-60">
                            {% else %}
                                <a href="{% url 'account_app:join' %}"
                                   class="effect-lily tm-post-link tm-pt-60">
                            {% endif %}
                            <div class="tm-post-link-inner">
                                <img src="{{ post_object.image.url }}" alt="{{ post_object.title }}"
                                     class="img-fluid" style="max-height: 600px; min-height: 600px">
                            </div>
                            {#                            <span class="position-absolute tm-new-badge">New</span>#}
                            <h2
                                    class="tm-pt-30 tm-color-primary tm-post-title">{{ post_object.title }}</h2>
                            </a>
                            <p class="tm-pt-30">
                                {{ post_object.body|truncatewords:50|truncatechars:50 }}
                            </p>
                            <div class="d-flex justify-content-between tm-pt-45">
                                <span class="tm-color-primary">
                                    {% if post_object.category.all.0 %}
                                        #{{ post_object.category.all.0 }}
                                    {% endif %}
                                    <br>
                                    {% if post_object.category.all.1 %}
                                        #{{ post_object.category.all.1 }}
                                    {% endif %}
                                    <br>
                                    {% if post_object.category.all.2 %}
                                        #{{ post_object.category.all.2 }}
                                    {% endif %}
                                    <br>
                                    {% if post_object.category.all.3 %}
                                        #{{ post_object.category.all.3 }}
                                    {% endif %}
                                    <br>
                                    {% if post_object.category.all.4 %}
                                        #{{ post_object.category.all.4 }}
                                    {% endif %}</span>
                            </div>
                            <div style="display: inline-block"
                                 class="alert alert-primary">{{ post_object.created_at.year }}
                                / {{ post_object.created_at.month }} / {{ post_object.created_at.day }}</div>
                            <div style="display: inline-block"
                                 class="alert alert-danger">{{ post_object.created_at.hour }}
                                : {{ post_object.created_at.minute }} : {{ post_object.created_at.second }}</div>
                            {% for author in all_authors %}
                                {% if author == post_object.author %}
                                    <div class="d-flex justify-content-between">
                                        <span class="tm-color-primary">Author ✍️ : <a
                                                href="{% url 'home_app:profile' author author.id %}">{{ post_object.author }}</a></span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <hr>
                        </article>
                    {% endif %}
                {% endfor %}
            </div>
            {% if post_objects.has_other_pages %}
                <div class="row tm-row tm-mt-100 tm-mb-75">
                    <div class="tm-prev-next-wrapper">
                        {% if post_objects.has_previous %}
                            <a href="?page={{ post_objects.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                               class="mb-2 tm-btn tm-btn-primary tm-prev-next tm-mr-20">Prev</a>
                        {% else %}
                            <a href=""
                               class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
                        {% endif %}
                        {% if post_objects.has_next %}
                            <a href="?page={{ post_objects.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                               class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
                        {% else %}
                            <a href="" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled">Next</a>
                        {% endif %}
                    </div>
                    <div class="tm-paging-wrapper">
                        <span class="d-inline-block mr-3">Page</span>
                        <nav class="tm-paging-nav d-inline-block">
                            <ul>
                                {% for item in post_objects.paginator.page_range %}
                                    {% if post_objects.number == item %}
                                        <li class="tm-paging-item active">
                                            <a href="?page={{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                               class="mb-2 tm-btn tm-paging-link">{{ item }}</a>
                                        </li>
                                    {% else %}
                                        <li class="tm-paging-item">
                                            <a href="?page={{ item }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                               class="mb-2 tm-btn tm-paging-link">{{ item }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% endif %}
        </main>
    </div>

{% endblock %}