PouyaTechBlog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from PouyaTechBlog import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("home_app.urls")),
                  path("", include("post_detail_app.urls")),
                  path("", include("account_app.urls")),
                  path("", include("contact_us_app.urls")),
                  path("addpost", include("add_post_app.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views

app_name = "account_app"

urlpatterns = [
    path("leave", views.leave, name="leave"),
    path("join", views.join, name="join"),
]

add_post_app/urls.py
from django.urls import path
from . import views

app_name = "post_add_app"

urlpatterns = [
    path("", views.add_post, name="add_post"),
]

contact_us_app/urls.py
from django.urls import path
from . import views

app_name = "contact_us_app"

urlpatterns = [
    path("contact_us", views.contact_us, name="contact_us"),
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("search", views.search, name="search_posts"),
    path("profile/<slug:slug>/<int:pk>", views.profile, name="profile"),
    path("edit-profile", views.edit_profile, name="edit_profile"),
    path("delete-profile", views.delete_profile, name="delete_profile"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}"> <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <!-- https://fonts.google.com/ -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">
    <link href="{% static 'js/like_ajax.js' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/site_logo.jpg' %}">
    <!--

    https://templatemo.com/tm-553-xtra-blog

    -->
</head>
<body>
<header class="tm-header" id="tm-header">
    <div class="tm-header-wrapper">
        <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="tm-site-header">
            <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>
            <h1 class="text-center" style="font-size: 32px;">PouyaTech Blog</h1>
        </div>
        <nav class="tm-nav" id="tm-nav">
            <ul>
                <li {% block home_page %} {% endblock %}><a href="{% url 'home_app:home' %}" class="tm-nav-link">
                    <i class="fas fa-home"></i>
                    Blog Home
                </a></li>
                {% if request.user.is_authenticated %}
                    <li {% block profile %} {% endblock %} class="tm-nav-item">
                        <a href="{% url 'home_app:profile' request.user request.user.id %}"
                           class="tm-nav-link">
                            <i class="fa fa-user-edit"></i>
                            Profile
                        </a></li>
                {% else %}
                    <li class="tm-nav-item">
                        <a href="{% url 'account_app:join' %}"
                           class="tm-nav-link">
                            <i class="fa fa-user-edit"></i>
                            Profile
                        </a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="tm-nav-item"><a href="{% url 'account_app:leave' %}" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Leave
                    </a></li>
                {% else %}
                    <li class="tm-nav-item"><a href="{% url 'account_app:join' %}" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Join
                    </a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li {% block add_post %} {% endblock %} class="tm-nav-item"><a
                            href="{% url 'post_add_app:add_post' %}" class="tm-nav-link">
                        <i class="fa fa-plus"></i>
                        Add post
                    </a></li>
                {% else %}
                    <li class="tm-nav-item"
                    ><a href="{% url 'account_app:join' %}" class="tm-nav-link">
                        <i class="fa fa-plus"></i>
                        Add post
                    </a></li>
                {% endif %}
                <li {% block contact_us %} {% endblock %}><a href="{% url 'contact_us_app:contact_us' %}"
                                                             class="tm-nav-link">
                    <i class="far fa-comments"></i>
                    Contact Us
                </a></li>
            </ul>
        </nav>
        <div class="tm-mb-65">
            <a rel="nofollow" href="{{ contact_us_info.youtube }}" class="tm-social-link">
                <i class="fab fa-youtube tm-social-icon"></i>
            </a>
            <a rel="nofollow" href="{{ contact_us_info.telegram }}" class="tm-social-link">
                <i class="fab fa-telegram-plane tm-social-icon"></i>
            </a>
            <a rel="nofollow" href="{{ contact_us_info.instagram }}" class="tm-social-link">
                <i class="fab fa-instagram tm-social-icon"></i>
            </a>
        </div>
    </div>
</header>

<main class="tm-main">
    <div class="row tm-row">
        <div class="col-12">
            <form method="GET" class="form-inline tm-mb-80 tm-search-form" action="{% url 'home_app:search_posts' %}">
                <input style="border-top-left-radius: 50px; border-bottom-right-radius: 50px;
                                         border-top-right-radius: 20px; border-bottom-left-radius: 20px"
                       class="form-control tm-search-input" name="q" type="text" placeholder="Search..."
                       aria-label="Search">
                <button style="border-radius: 25px" class="tm-search-button" type="submit">
                    <i class="fas fa-search tm-search-icon" style="" aria-hidden="true"></i>
                </button>
            </form>
        </div>
    </div>
</main>

{% block content %}

{% endblock %}

<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/templatemo-script.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
</body>
</html>